### ISSUE TITLE
.flew-row instead of .flex-row

### ISSUE THREAD

**Issue by kittenparry** [kittenparry/economy-board-game-electron#11]
At [line 104](https://github.com/kittenparry/economy-board-game-electron/blob/f746479d11a6bb37660229fdb8de3d4c5666db1b/game/main_window.css#L104) of styling, should be changed to `flex-row`.

**Comment by manuelizo** [comment]
I can change it if it's ok for you. :)

**Comment by manuelizo** [comment]
I have just made the pull request.

**Comment by kittenparry** [comment]
I actually didn't expect anyone to look into it but tagged as `good first issue` because it was an easy fix. Thank you! I'll accept it momentarily.

**Comment by manuelizo** [comment]
I was looking for giving some help here in Github, and I found your project with some issues.. If you need more help just talk to me and I'll do as much as I can! Have a good day :smile:

**Comment by kittenparry** [comment]
Most issues need simple fixes, I just couldn't get around doing them and instead noted them down to fix later. I will handle them at one point, but if it doesn't bother you, I wouldn't mind accepting pull requests. Thanks again!
